# This yaml deploys telepreco BFF alone on k8s.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-{{ .Release.Name }}-{{ .Values.label.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.appBffLabel }}
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always