# This yaml deploys telepreco BFF alone on k8s.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-poc-telepreco-bff
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: poc-telepreco-bff
    spec:
      containers:
      - name: mcarbabybfftelepreco
        image: rodoflho/mcarbabybfftelepreco:latest