# This yaml deploys telepreco BFF alone on k8s.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-poc-telepreco-bff
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: poc-telepreco-bff
    spec:
      containers:
      - name: mcarbabybfftelepreco
        image: mcarimageregistry.azurecr.io/baby-bff-telepreco:latest
        imagePullPolicy: Always