apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-poc-telepreco-cliente
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: poc-telepreco-bff-cliente
    spec:
      containers:
      - name: mcarbabymicroservicecliente
        image: mcarimageregistry.azurecr.io/baby-microservice-cliente:latest
        imagePullPolicy: Always