apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-poc-telepreco-sac
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: poc-telepreco-bff-sac
    spec:
      containers:
      - name: mcarbabymicroservicesac
        image: rodoflho/mcarbabymicroservicesac:latest
        imagePullPolicy: Always