apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-poc-telepreco-atendimento
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: poc-telepreco-bff-atendimento
    spec:
      containers:
      - name: mcarmicroserviceattendance
        image: rodoflho/mcarmicroserviceattendance:latest
        imagePullPolicy: Always