apiVersion: batch/v1
kind: Job
metadata:
  name: job-cluster-init
  labels:
    jobgroup: jobs-cluster-init
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
spec:
  template:
    metadata:
      name: job-cluster-init
      labels:
        jobgroup: jobs-cluster-init
    spec:
      containers:
      - name: jobclusterinit
        image: rodoflho/mcarmicroserviceclusterinitjob:latest
      restartPolicy: OnFailure