apiVersion: v1
kind: Service
metadata:
  name: svc-poc-telepreco-pessoa
  labels: 
    app: poc-telepreco-pessoa
spec:
  type: ClusterIP
  ports:
  - port: 11005
    targetPort: 80
  selector:
    app: poc-telepreco-bff-pessoa
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-poc-telepreco-pessoa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: poc-telepreco-bff-pessoa
    spec:
      containers:
      - name: mcarmicroservicepessoa
        image: rodoflho/mcarmicroservicepessoa:latest