# This yaml deploys telepreco BFF alone on k8s.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-poc-telepreco-bff-asterisk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: poc-telepreco-bff-asterisk
    spec:
      containers:
      - name: mcarbabybffteleprecoasterisk
        image: mcarimageregistry.azurecr.io/baby-bff-telepreco-asterisk:latest
        imagePullPolicy: Always