apiVersion: v1
kind: Service
metadata:
  name: svc-poc-telepreco-bff-asterisk
  labels: 
    app: poc-telepreco-bff-asterisk
spec:
  type: ClusterIP
  ports:
  - port: 11005
    name: http1-port
    targetPort: 5005
  - port: 11006
    name: http2-port
    targetPort: 5006
  selector:
    app: poc-telepreco-bff-asterisk
  