apiVersion: v1
kind: Service
metadata:
  name: svc-poc-telepreco-sac
  labels: 
    app: poc-telepreco-sac
spec:
  type: ClusterIP
  ports:
  - port: 11005
    targetPort: 80
  selector:
    app: poc-telepreco-bff-sac
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-poc-telepreco-sac
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: poc-telepreco-bff-sac
    spec:
      containers:
      - name: mcarbabymicroservicesac
        image: rodoflho/mcarbabymicroservicesac:latest