apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-poc-telepreco-bff
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: poc-telepreco-bff
    spec:
      containers:
      - name: mcarbabybfftelepreco
        image: rodoflho/mcarbabybfftelepreco:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-poc-telepreco-bff
  labels: 
    app: poc-telepreco-bff
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
  selector:
    app: poc-telepreco-bff
  