apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-poc-telepreco-estoque
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: poc-telepreco-bff-estoque
    spec:
      containers:
      - name: mcarbabymicroserviceestoque
        image: mcarimageregistry.azurecr.io/baby-microservice-estoque:latest
        imagePullPolicy: Always