apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-poc-telepreco-orcamento
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: poc-telepreco-bff-orcamento
    spec:
      containers:
      - name: mcarmicroserviceorcamento
        image: mcarimageregistry.azurecr.io/microservice-orcamento:latest
        imagePullPolicy: Always