apiVersion: v1
kind: Service
metadata:
  name: svc-poc-telepreco-frontend
  labels: 
    app: poc-telepreco-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: poc-telepreco-frontend
  